// Auto-generated by mbl-actionhub emit-cmp-metadata.yml — seed authored 2026-05-30
// by library-runtime-observability epic Phase 02 T5 (AC #10).
//
// DO NOT HAND-EDIT. Regenerated post-publish by mbl-actionhub workflow.
//
// Consumed by per-cmp-* CmpMetadataGenTask (Phase 02 T3) which reads these
// `extra["..."]` properties at compile time to generate commonMain/.../CmpMetadata.kt.
//
// Initial seed values mirror published versions in libs.versions.toml as of
// 2026-05-30. Next publish refreshes automatically via the mbl-actionhub workflow.

// Library umbrella version (from gradle.properties: kmptoolkit.version)
val kmpToolkitVersion = providers.gradleProperty("kmptoolkit.version").orElse("UNKNOWN").get()

// Per-cmp-* version + artifact constants
extra["cmp_observe_version"] = kmpToolkitVersion
extra["cmp_observe_artifact"] = "io.github.mobilebytelabs:cmp-observe"

extra["cmp_observe_koin_version"] = kmpToolkitVersion
extra["cmp_observe_koin_artifact"] = "io.github.mobilebytelabs:cmp-observe-koin"

extra["cmp_share_version"] = kmpToolkitVersion
extra["cmp_share_artifact"] = "io.github.mobilebytelabs:cmp-share"

extra["cmp_share_compose_version"] = kmpToolkitVersion
extra["cmp_share_compose_artifact"] = "io.github.mobilebytelabs:cmp-share-compose"

extra["cmp_intent_launcher_version"] = kmpToolkitVersion
extra["cmp_intent_launcher_artifact"] = "io.github.mobilebytelabs:cmp-intent-launcher"

extra["cmp_intent_launcher_compose_version"] = kmpToolkitVersion
extra["cmp_intent_launcher_compose_artifact"] = "io.github.mobilebytelabs:cmp-intent-launcher-compose"

extra["cmp_app_intents_version"] = kmpToolkitVersion
extra["cmp_app_intents_artifact"] = "io.github.mobilebytelabs:cmp-app-intents"

extra["cmp_app_intents_compose_version"] = kmpToolkitVersion
extra["cmp_app_intents_compose_artifact"] = "io.github.mobilebytelabs:cmp-app-intents-compose"

extra["cmp_network_monitor_version"] = kmpToolkitVersion
extra["cmp_network_monitor_artifact"] = "io.github.mobilebytelabs:cmp-network-monitor"

extra["cmp_network_monitor_compose_version"] = kmpToolkitVersion
extra["cmp_network_monitor_compose_artifact"] = "io.github.mobilebytelabs:cmp-network-monitor-compose"

extra["cmp_clipboard_version"] = kmpToolkitVersion
extra["cmp_clipboard_artifact"] = "io.github.mobilebytelabs:cmp-clipboard"

extra["cmp_toast_version"] = kmpToolkitVersion
extra["cmp_toast_artifact"] = "io.github.mobilebytelabs:cmp-toast"

extra["cmp_bubble_version"] = kmpToolkitVersion
extra["cmp_bubble_artifact"] = "io.github.mobilebytelabs:cmp-bubble"

extra["cmp_open_url_version"] = kmpToolkitVersion
extra["cmp_open_url_artifact"] = "io.github.mobilebytelabs:cmp-open-url"

extra["cmp_deep_link_version"] = kmpToolkitVersion
extra["cmp_deep_link_artifact"] = "io.github.mobilebytelabs:cmp-deep-link"

extra["cmp_in_app_update_version"] = kmpToolkitVersion
extra["cmp_in_app_update_artifact"] = "io.github.mobilebytelabs:cmp-in-app-update"

extra["cmp_remote_config_version"] = kmpToolkitVersion
extra["cmp_remote_config_artifact"] = "io.github.mobilebytelabs:cmp-remote-config"
extra["cmp_remote_config_compose_artifact"] = "io.github.mobilebytelabs:cmp-remote-config-compose"

extra["cmp_product_tickets_version"] = kmpToolkitVersion
extra["cmp_product_tickets_artifact"] = "io.github.mobilebytelabs:cmp-product-tickets"

extra["cmp_firebase_version"] = kmpToolkitVersion
extra["cmp_firebase_artifact"] = "io.github.mobilebytelabs:cmp-firebase"

extra["cmp_pdf_generator_version"] = kmpToolkitVersion
extra["cmp_pdf_generator_artifact"] = "io.github.mobilebytelabs:cmp-pdf-generator"

extra["cmp_library_version"] = kmpToolkitVersion
extra["cmp_library_artifact"] = "io.github.mobilebytelabs:cmp-library"
