/*
 * Copyright 2026 MobileByteLabs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 */
package com.mobilebytelabs.kmptoolkit.pdfgenerator

import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.MutableSharedFlow
import kotlinx.coroutines.flow.asSharedFlow

/**
 * Where a generated PDF goes on a target with no OS document surface.
 *
 * tvOS, watchOS, Linux, Windows and WASI can all *produce* a PDF — see [TextPdfWriter] — but none
 * of them offers a share sheet, a print dialog or a save panel this library can drive. Rather than
 * refuse those outputs, the bytes are handed to the app, which knows where they should go: a
 * backend upload, a companion device, a path of its own choosing.
 *
 * ```kotlin
 * PdfHost.onOutput = { bytes, fileName, output ->
 *     File("/srv/reports/$fileName").writeBytes(bytes)
 *     "file:///srv/reports/$fileName"          // returned as PdfResult.Success.uri
 * }
 * ```
 *
 * [PdfOutput.ByteArrayOutput] never needs a handler — the bytes are returned directly, so the
 * common "generate and upload" case works with no setup at all.
 */
public object PdfHost {

    /**
     * Receives generated bytes for every output other than [PdfOutput.ByteArrayOutput].
     *
     * Return a URI describing where they landed, or `null` if the request could not be honoured —
     * which surfaces to the caller as a typed [PdfError.UnsupportedFeature].
     */
    public var onOutput: ((bytes: ByteArray, fileName: String, output: PdfOutput) -> String?)? = null

    /** Whether an app handler is registered. */
    public val isConfigured: Boolean get() = onOutput != null

    /** Unregister the handler — intended for tests. */
    public fun reset() {
        onOutput = null
    }
}

/**
 * `PdfGenerator` for the targets with no HTML renderer — tvOS, watchOS, Linux, Windows, WASI.
 *
 * Generation is real: [TextPdfWriter] emits a valid PDF 1.4 document with text, headings, tables
 * and pagination. What is missing is HTML/CSS layout, so [generateFromHtml] strips the markup to
 * text rather than pretending to lay it out — a caller needing real layout wants a Tier-1 target,
 * and should be able to tell which they got.
 */
public actual class PdfGenerator public actual constructor() {

    private val progress = MutableSharedFlow<PdfProgressEvent>(extraBufferCapacity = 16)

    public actual suspend fun generateAndSharePdf(htmlContent: String, fileName: String, pageConfig: PageConfig) {
        generateFromHtml(
            html = htmlContent,
            output = PdfOutput.Share,
            pageConfig = pageConfig,
            fileName = fileName,
        )
    }

    public actual suspend fun generate(
        document: PdfDocument,
        output: PdfOutput,
        options: PdfGeneratorOptions,
        fileName: String,
    ): PdfResult {
        progress.tryEmit(PdfProgressEvent.Started)
        val bytes = runCatching { TextPdfWriter.write(document) }
            .getOrElse { return PdfResult.Failure(PdfError.EngineFailure(it)) }
        progress.tryEmit(PdfProgressEvent.Finalizing)
        return deliver(bytes, ensurePdfFileName(fileName), output)
    }

    public actual suspend fun generateFromHtml(
        html: String,
        output: PdfOutput,
        pageConfig: PageConfig,
        branding: PdfBranding,
        options: PdfGeneratorOptions,
        fileName: String,
    ): PdfResult {
        // The markup is preserved as an Html element so TextPdfWriter can strip it consistently
        // with how it handles PdfElement.Html anywhere else.
        val document = PdfDocument(
            pages = listOf(PdfPage(listOf(PdfElement.Html(html)))),
            config = pageConfig,
            branding = branding,
        )
        return generate(document, output, options, fileName)
    }

    public actual fun progressFlow(): Flow<PdfProgressEvent> = progress.asSharedFlow()

    private fun deliver(bytes: ByteArray, fileName: String, output: PdfOutput): PdfResult {
        if (output is PdfOutput.ByteArrayOutput) {
            progress.tryEmit(PdfProgressEvent.Complete(bytes.size))
            return PdfResult.Success(bytes = bytes, byteCount = bytes.size)
        }

        val handler = PdfHost.onOutput ?: return PdfResult.Failure(
            PdfError.UnsupportedFeature(
                "$output has no OS surface on this target. The PDF was generated successfully — " +
                    "use PdfOutput.ByteArrayOutput to receive the bytes, or set PdfHost.onOutput " +
                    "to route them yourself.",
            ),
        )

        val uri = handler(bytes, fileName, output) ?: return PdfResult.Failure(
            PdfError.UnsupportedFeature("PdfHost.onOutput declined $output"),
        )
        progress.tryEmit(PdfProgressEvent.Complete(bytes.size))
        // Callback outputs expect the URI through their own channel as well.
        if (output is PdfOutput.Uri) output.callback(uri)
        return PdfResult.Success(uri = uri, byteCount = bytes.size)
    }
}
