import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    `kotlin-dsl`
    alias(libs.plugins.vanniktech.mavenPublish)
    // Gradle Plugin Portal half of the dual publish. Maven Central stays the SoT
    // (same version, published first); the Portal is a mirror so that a consumer with
    // Gradle's DEFAULT pluginManagement repositories — which include gradlePluginPortal()
    // but not mavenCentral() — can apply this plugin with zero repository setup.
    alias(libs.plugins.gradle.plugin.publish)
    // Opts this module into root's kover aggregation (see KoverConventionPlugin).
    id("io.github.mobilebytelabs.kmptoolkit.kover")
}

// ============================================================================
// LIBRARY CONFIGURATION
// ============================================================================
// Version is locked to kmptoolkit.version — the plugin enforces build-side setup for a
// SPECIFIC cmp-firebase release (its Kotlin floor, its static-framework requirement), so a
// plugin/library version skew would enforce the wrong contract.
group = "io.github.mobilebytelabs"
version = providers.gradleProperty("kmptoolkit.version").get()

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
    // Produced here rather than via vanniktech's JavadocJar.Empty(): with
    // `java-gradle-plugin` also contributing publications, the Empty() variant leaves
    // GenerateModuleMetadata without a declared dependency on emptyJavadocJar and the
    // publish fails validation. This is the shape kmp-product-flavors ships.
    withJavadocJar()
    withSourcesJar()
}

kotlin {
    compilerOptions {
        jvmTarget = JvmTarget.JVM_17
        // Emit Kotlin 2.0 metadata so consumers on older Gradle can read this plugin's
        // classes. Gradle's embedded `kotlin-dsl` compiler is Kotlin 2.0.x below Gradle 9.5;
        // metadata newer than it can read fails at apply-time with
        //   "Class '…' was compiled with an incompatible version of Kotlin.
        //    The actual metadata version is 2.4.0, but the compiler … can read up to 2.1.0."
        // Nothing here needs a post-2.0 language feature, so this is metadata-level only.
        languageVersion.set(org.jetbrains.kotlin.gradle.dsl.KotlinVersion.KOTLIN_2_0)
        apiVersion.set(org.jetbrains.kotlin.gradle.dsl.KotlinVersion.KOTLIN_2_0)
    }
    explicitApi()
}

// The plugin adds the cmp-firebase dependency at its OWN version, so applying the plugin
// can never pair a consumer with a mismatched library. Generated rather than hardcoded so
// the constant cannot drift from kmptoolkit.version.
val generateVersionConstant =
    tasks.register("generateVersionConstant") {
        val versionValue = version.toString()
        val outputDir = layout.buildDirectory.dir("generated/version/kotlin")
        inputs.property("version", versionValue)
        outputs.dir(outputDir)
        doLast {
            val pkgDir = outputDir.get().asFile.resolve("io/github/mobilebytelabs/kmptoolkit/firebase/gradle")
            pkgDir.mkdirs()
            pkgDir.resolve("CmpFirebaseVersion.kt").writeText(
                """
            |// Generated by :cmp-firebase-gradle-plugin build — do not edit.
            |package io.github.mobilebytelabs.kmptoolkit.firebase.gradle
            |
            |internal const val CMP_FIREBASE_VERSION: String = "$versionValue"
            |
                """.trimMargin(),
            )
        }
    }

kotlin.sourceSets.named("main") {
    kotlin.srcDir(generateVersionConstant)
}

dependencies {
    // compileOnly: the consumer's build already has the Kotlin Gradle plugin on its
    // classpath. Bundling it would risk a version clash with whatever KGP they apply.
    compileOnly(libs.kotlin.gradle.plugin)

    testImplementation(libs.kotlin.test)
    testImplementation(libs.kotlin.test.junit)
    testImplementation(libs.kotlin.gradle.plugin)
}

tasks {
    validatePlugins {
        enableStricterValidation = true
        failOnWarning = true
    }
}

gradlePlugin {
    // Required by com.gradle.plugin-publish for the Portal listing.
    // website points at the PLUGIN's own README, not the repo root. The Portal review rejected
    // the first submission with "Your plugin lacks documentation" because a reviewer following
    // the repo-root link found a large toolkit README that never mentioned this plugin.
    website.set("https://github.com/MobileByteLabs/KmpToolkit/blob/dev/cmp-firebase-gradle-plugin/README.md")
    vcsUrl.set("https://github.com/MobileByteLabs/KmpToolkit")

    plugins {
        register("cmpFirebase") {
            id = "io.github.mobilebytelabs.firebase"
            implementationClass =
                "io.github.mobilebytelabs.kmptoolkit.firebase.gradle.CmpFirebasePlugin"
            displayName = "Firebase for Kotlin Multiplatform — build setup"
            description =
                "Configures a Kotlin Multiplatform project to use Firebase via cmp-firebase. " +
                "Adds the cmp-firebase dependency at a matching version, forces isStatic=true on " +
                "every Apple framework (Firebase's SwiftPM products are static libraries, so a " +
                "dynamic framework compiles and links but crashes at launch), and fails the build " +
                "with an actionable message when Kotlin is below 2.4.20, where the transitive " +
                "SwiftPM resolution that pulls firebase-ios-sdk does not exist and the build " +
                "otherwise dies with an unrelated-looking \"ld: framework 'FirebaseCore' not " +
                "found\". Documentation: " +
                "https://github.com/MobileByteLabs/KmpToolkit/blob/dev/cmp-firebase-gradle-plugin/README.md"
            tags = listOf("kotlin-multiplatform", "kmp", "firebase", "ios", "swiftpm", "analytics", "crashlytics")
        }
    }
}

// ============================================================================
// MAVEN CENTRAL PUBLISHING CONFIGURATION
// ============================================================================
// GradlePlugin() also publishes the plugin MARKER artifact
// (io.github.mobilebytelabs.firebase:…gradle.plugin), which is what lets a
// consumer resolve `plugins { id("…") version "…" }` from Maven Central. No Gradle Plugin
// Portal account or release step is required — consumers only need mavenCentral() in their
// settings.gradle.kts `pluginManagement.repositories`, which nearly every KMP project has.
// Sign only where a key exists: CI exports ORG_GRADLE_PROJECT_signingInMemoryKey, and a
// human can opt in locally with -PsignPublications=true. Unconditional signAllPublications()
// makes `publishToMavenLocal` fail with "No configured signatory" on any dev machine, which
// blocks the one cheap way to verify a publication end-to-end before release.
val signPublications: Boolean =
    System.getenv("ORG_GRADLE_PROJECT_signingInMemoryKey") != null ||
        providers.gradleProperty("signPublications").orNull?.toBoolean() == true

mavenPublishing {
    coordinates(group.toString(), "cmp-firebase-gradle-plugin", version.toString())
    if (signPublications) {
        signAllPublications()
    }

    pom {
        name = "CMP Firebase Gradle Plugin"
        description =
            "Build-side setup enforcement for cmp-firebase — static Apple frameworks + Kotlin floor check."
        inceptionYear = "2026"
        url = "https://github.com/MobileByteLabs/KmpToolkit/"

        licenses {
            license {
                name = "The Apache License, Version 2.0"
                url = "https://www.apache.org/licenses/LICENSE-2.0.txt"
                distribution = "repo"
            }
        }

        developers {
            developer {
                id = "MobileByteLabs"
                name = "MobileByteLabs"
                url = "https://github.com/MobileByteLabs"
            }
        }

        scm {
            url = "https://github.com/MobileByteLabs/KmpToolkit/"
            connection = "scm:git:git://github.com/MobileByteLabs/KmpToolkit.git"
            developerConnection = "scm:git:ssh://git@github.com/MobileByteLabs/KmpToolkit.git"
        }
    }
}

tasks.withType<Sign>().configureEach {
    onlyIf { signPublications }
}
